### ISSUE TITLE
Assertion `occs.size() == 1' failed

### ISSUE THREAD

**Issue by fbemm** [ekg/seqwish#1]
Hey,

I am trying to align 4 times 40Mb stored in a combined fasta with seqwish and get the following:

`seqindex.cpp:184: size_t seqwish::seqindex_t::rank_of_seq_named(const string&): Assertion 'occs.size() == 1' failed.`

Any idea where to start debugging?

Thx,
F

**Comment by apregier** [comment]
I just encountered the same issue.  It seems that the 'locate' API returns entries where the query is a substring of the contig name (i.e. query of ">1" will return both ">1" and ">11".  Unfortunately I am not seeing an easy fix with the sdsl API (although I might be missing something).  Workaround would be to assign sequence names that are not substrings of each other.

**Comment by ekg** [comment]
Thank you both for uncovering this mistake! The fix in seqwish should be
easy. We just need to append a " " to the search string.

**Comment by ekg** [comment]
I was able to reproduce this, so I expect it to resolve your problems as well. Let me know if otherwise.

**Comment by VidJa** [comment]
I'm running into this same issue, even after using the sha256 hashes from each sequence as sequence IDs
I've compiled from today's master

seqindex.cpp:210: size_t seqwish::seqindex_t::rank_of_seq_named(const string&): Assertion `occs.size() == 1' failed.

**Comment by ekg** [comment]
Would you be able to share a minimap test case that reproduces this? This
error could have other causes.

**Comment by VidJa** [comment]
Hi Erik, just to let you know I got it working. I was using multiple -s <seq.fasta> on the commandline, but collapsing them in one files made it work.

**Comment by ekg** [comment]
Great!
