### ISSUE TITLE
How should a simple test be performed after seqwish is installed

### ISSUE THREAD

**Issue by Wenmj201582** [ekg/seqwish#100]
When I run the **make test** operation under the seqwish-v0.7.6/test directory, I encountered the following errors. 
What does expected mean, and how can I solve such errors? 
Please give me guidance and help. 
Thank you
![image](https://user-images.githubusercontent.com/77086644/187067823-ee119d95-4d90-4afa-978c-1ba6fd947491.png)

**Comment by AndreaGuarracino** [comment]
Hi @Wenmj201582, could you please provide more information about your system and how you installed `seqwish`?

I just ran the following instructions, without getting any errors:

```
wget -c https://github.com/ekg/seqwish/releases/download/v0.7.6/seqwish-v0.7.6.tar.gz
tar -xvf seqwish-v0.7.6.tar.gz
cd seqwish-v0.7.6
cmake -H. -DCMAKE_BUILD_TYPE=Release -Bbuild && cmake --build build -- -j 16
cd test
make test
```

**Comment by Wenmj201582** [comment]
Thank you very much. 
This problem has been solved.
