### ISSUE TITLE
reducing local graph complexity

### ISSUE THREAD

**Issue by ekg** [ekg/seqwish#16]
Graphs produced from the mutual alignment of noisy reads can result in surprisingly complex structures that are more representative of the error process inherent in the input reads than structures that are biologically relevant.

For instance, using some canu-corrected ultra long ONT reads, we can use seqwish to get a circular E. coli assembly without any typical assembly steps. I first kept only alignments with a block length of the N50 of the reads (~100kb). Then I filtered the graph (using odgi) to remove tips and other low-coverage parts of the assembly with path coverage <30X. The expected coverage is ~60X.

![Screenshot from 2019-05-21 16-25-23](https://user-images.githubusercontent.com/145425/58104578-4a8d1d00-7be5-11e9-8abb-600a821508e4.png)

The global structure of this graph matches our expectation. It's basically a single circle. There are a few medium size indels scattered throughout, which could represent standing variation in the sequenced strain, or a low rate of alignment error due to ambiguity, but it's pretty much what we would expect.

However, zooming into the local structure shows us that a very complicated solution has been found:

![Screenshot from 2019-05-21 15-53-31](https://user-images.githubusercontent.com/145425/58101848-9ab5b080-7be0-11e9-8780-d7db0292eca1.png)

![Screenshot from 2019-05-21 15-54-15](https://user-images.githubusercontent.com/145425/58101913-b4ef8e80-7be0-11e9-9a1b-4374960d17fd.png)

![Screenshot from 2019-05-21 15-54-53](https://user-images.githubusercontent.com/145425/58101955-ca64b880-7be0-11e9-8364-8268d870d609.png)

The graph is linear from a high level, but not locally.

This could represent a bug in the interpretation of the alignments. I'll check on that. I haven't seen it in other cases, so I suspect it has to do with differential alignment of reads that tend to have repeat related errors across small repeated sequences in the genome.

If this isn't a bug in seqwish's interpretation of alignments, then it should be possible to resolve this by changing the alignment input in some way. It's not clear to me if seqwish itself is the right place to try to resolve this. I've attempted to keep the algorithm as clean as possible, and simply induce the variation graph implied by a set of alignments between some sequences. Here, I get the impression that I could implement some kind of filter that prevents this kind of collapse. There is already one such limit, which is the only free parameter in seqwish:

```
      -r[N], --repeat-max=[N]           limit transitive closure to include no
                                        more than N copies of a given input base
```

However, the implementation of this is order dependent. We should collect each base's transitive closure first before deciding if we should break it apart based on a parameter like this.

If implemented in a well defined way, this could be set to the expected coverage, or some small threshold over or under it in order to mitigate collapse.

**Comment by rchikhi** [comment]
Hi Erik,
Intriguing!

1) Could this be a matter of normalizing alignments? 

2) I'd like to understand how seqwish works, perhaps not the low-level construction details at first but at a high level how the graph is constructed. The README says that Q is a concatenation of input sequences and A is their alignment. I'm assuming Q is the `-s` parameter (FASTA file) and A is the `-p` parameter (PAF). Then the intuition behind S, N, and P are a bit less clear to me but N and P seem to be intermediate objects. Is P the same object as in the "paths (P)" mentioned later in that README section in the context of GFA. Seems that the node of the graph is S; but S is defined as a vector, which is odd for a nodeset.

Thanks,
Rayan

**Comment by ekg** [comment]
Hi @rchikhi !

> Could this be a matter of normalizing alignments?

Yes, perhaps this is the main issue. I'm just trusting whatever comes out of minimap2, and that could have very different representations of the alignment depending on a number of factors. I haven't investigated this, but should.

> I'd like to understand how seqwish works, perhaps not the low-level construction details at first but at a high level how the graph is constructed.

The names used in the README don't match GFA. I probably should remove reference to the namespaces in GFA to avoid confusion. Sorry about this. Forget the GFA namespaces as you read the algorithm description.

At a high level, seqwish is inducing the graph implied by the set of alignments and the sequences in the input. It works in a series of steps:

1. [Index the input sequence set to provide name to sequence mapping.](https://github.com/ekg/seqwish/blob/4df3c67400078b3790181f5cc2b20e4e567165c4/src/main.cpp#L72-L75)
2. [Compute the "alignment graph" in which we have a node for each sequence base and an edge for each assertion of equivalence between bases given by the input alignment set.](https://github.com/ekg/seqwish/blob/4df3c67400078b3790181f5cc2b20e4e567165c4/src/main.cpp#L77-L93) 
3. [Find the transitive closure of the alignment links in this graph. Each closure results in a single base of sequence in the final graph.](https://github.com/ekg/seqwish/blob/4df3c67400078b3790181f5cc2b20e4e567165c4/src/main.cpp#L95-L110) In this step, we project each sequence into this set of bases of the final graph.
4. [Use the input sequence to output sequence mapping to construct the set of links of the graph.](https://github.com/ekg/seqwish/blob/4df3c67400078b3790181f5cc2b20e4e567165c4/src/main.cpp#L112-L129) Here, we're writing a link pair for every pair of bases in the output sequence space that is connected in one of our input sequences. The edges in the output graph are a unique subset of these.
5. [Compress the non-bifurcating regions of the graph and provide a compact set of node ids for the output graph.](https://github.com/ekg/seqwish/blob/4df3c67400078b3790181f5cc2b20e4e567165c4/src/main.cpp#L131-L141)
6. [Use the established sorted/indexed arrays to write the output in GFA or VGP format.](https://github.com/ekg/seqwish/blob/4df3c67400078b3790181f5cc2b20e4e567165c4/src/main.cpp#L143-L151)

This is detailed in [my thesis](https://github.com/ekg/thesis), which you should be able to clone and build, and I am preparing a manuscript based on what's already written there.

The main idea is to work on atomic basepairs rather than on sequences. For reasonable sized problems, this would be impossible to do in main memory unless we had terabytes available, so all of the data is stored on disk in sorted arrays (mmmultimap).

**Comment by rchikhi** [comment]
Hi @ekg! Thanks for the detailed explanations. 

RE thesis: at first I thought that I could use the thesis document I saw in an earlier tweet (that linked to https://github.com/ekg/thesis/releases) but it seems that your thesis was updated recently. I compiled the latest version (it worked using `make`) and didn't really see much changes regarding seqwish, which is described in section 2.2.6 and looks like what's in the README of the present repository.

**Comment by ekg** [comment]
That's right @rchikhi! I forgot that that section wasn't changed at all. Sorry this didn't help things further. 

At present I am figuring out how to convert the intermediate representations into cgranges style sorted intervals rather than raw pairs of scalar values. This reduced the size of the alignment array by a factor of 100, and I'd like to do it for other cases where possible, but it is a little tricky to implement.

**Comment by rchikhi** [comment]
I see, that makes sense then :) Okay I'll use your high-level explanation written above to try to understand.

**Comment by ekg** [comment]
An update to `--repeat-max` should help this. Setting 1 will prevent self-loops. Using the `-k` parameter will remove very short matches. Together, these can be used to mitigate the problem.
