### ISSUE TITLE
Option for acyclic reference path

### ISSUE THREAD

**Issue by glennhickey** [ekg/seqwish#19]
How feasible would it be to force one of the input sequences (ex hg38) to be acyclic in the output graph?

**Comment by ekg** [comment]
You can add -r 1 to the seqwish call. Is the cyclicity causing problems?

**Comment by glennhickey** [comment]
Yeah, they're causing trouble for `vg deconstruct`, it seems.  I was assuming that cycles get spanned by snarls (which is true), but I also have logic where if a snarl is too big to handle, it recurses on child snarls.  These snarls can be within cyclces, and I'm not handling that case properly.  I'm trying to figure out the best way to fix deconstruct now, but was curious if I could just flatten things out in the meantime

**Comment by ekg** [comment]
That makes sense. You can try this. It will prevent cycling by stopping the
transitive closure if it encounters the same sequence twice.

**Comment by ekg** [comment]
Did -r 1 solve this problem for you?

**Comment by glennhickey** [comment]
Hmm, I honestly don't remember.  I think I fixed deconstruct to be more robust (judging from the name of this commit https://github.com/vgteam/vg/commit/ad7d26c8007d20ea14a74bec1a75fc29ff4a5e82#diff-d905c05327c6f07e310f14d41c42d84f0 ).  

I do remember being blocked on  #18.  I guess I should try that data with the latest seqish (it's been a while) to see if still comes up
