### ISSUE TITLE
Aborted (core dumped) when building graph from 8 yeast genomes

### ISSUE THREAD

**Issue by subwaystation** [ekg/seqwish#30]
Hi @ekg ,

I tried to induce a variation graph from one fasta file with 8 yeast genomes via

```
ubuntu@pantograph2:~/sh$ ../software/seqwish/git/seqwish-0.1/bin/seqwish -s yeast_l10k_R64-1-1.fa -t 28 -g yeast_l10k_R64-1-1.gfa
seqwish: /home/ubuntu/vol1/software/seqwish/git/seqwish-0.1/src/main.cpp:98: int main(int, char**): Assertion `false' failed.
Aborted (core dumped)
```

As you suggested I went `vg view` -- `vg paths` -- `cat new.fasta vg_paths.fasta`. The `.fa.fai` of the new `.fasta` looks quite good.
But `seqwish` just stops. I expect that it could be a naming scheme problem within the fasta headers?

You can get all the relevant data via `wget 
http://fex.belwue.de/fop/Q60OHDwU/seqwish_yeast_ggbhtu2k19.tar.gz`

Thanks for your feedback!

**Comment by ekg** [comment]
The problem is that you're not supplying any PAF file defining the alignment. I thought this was checked, but it looks like I wasn't careful.

You'll need to make that via something like scripts/pan-minimap2 or `minimap2 -X -c -x asm20`.

**Comment by subwaystation** [comment]
So I can't read your README. Will try that tomorrow.

**Comment by subwaystation** [comment]
So the error was on my side.
