### ISSUE TITLE
Tag new release and create Bioconda recipe

### ISSUE THREAD

**Issue by heuermh** [ekg/seqwish#34]
I may have done something wrong building a Docker image (been spoiled by Bioconda/Biocontainers for too long :smile:), it works ok interactively
```
$ docker run -it heuermh/seqwish-dev /bin/bash
root@c523ee06a258:/seqwish# seqwish --help
  seqwish {OPTIONS}

    seqwish: a variation graph inducer
...

$ docker run -it heuermh/seqwish-dev seqwish
  seqwish {OPTIONS}

    seqwish: a variation graph inducer
```

but not when run by Nextflow (copied from `.command.run`)
```
$ docker run -i \
  -v /Users/heuermh/working/viral-assembly/work:/Users/heuermh/working/viral-assembly/work \
  -v "$PWD":"$PWD" \
  -w "$PWD" \
  --entrypoint /bin/bash heuermh/seqwish-dev \
  -c "/bin/bash -ue /Users/heuermh/working/viral-assembly/work/2a/bec35575e4f91b50b4a41bb6a73e61/.command.sh"

/Users/heuermh/working/viral-assembly/work/2a/bec35575e4f91b50b4a41bb6a73e61/.command.sh:
line 2: seqwish: command not found
```

[Docker file](https://github.com/heuermh/docker-linuxbrew-bio/blob/master/seqwish-dev/Dockerfile), [Docker Hub repo](https://hub.docker.com/repository/docker/heuermh/seqwish-dev)

Perhaps the best thing to do would be to tag a new release and create a Bioconda recipe.

**Comment by ekg** [comment]
Ok I can do that. Will in the morning.

**Comment by ekg** [comment]
FYI we (me and @urbanslug) have found two bugs with the current master. But
an unstable release can be cut.

**Comment by heuermh** [comment]
Thanks!  Or if using the last tag v0.2 is better, I don't mind either way.

**Comment by foreveremain** [comment]
hi - any progress on that bioconda recipe :) just trying a build on osx so may be able to add another platform.

**Comment by ekg** [comment]
Use v0.2.1. I've just tagged it.

**Comment by foreveremain** [comment]
mmapallocator isn't playing on x86_64-apple-darwin13.4.0 - probably something simple (of course) but my clang is rusty - errors all look similar to:
./mmappable_vector.h:117:10: error: no member named '_M_impl' in 'std::__1::vector<int, mmap_allocator_namespace::mmap_allocator<int> >'
                        Base::_M_impl._M_finish = Base::_M_impl._M_start + n;

pausing for now - will pick up again in 24hrs or so unless someone throws me a bone here :)

**Comment by ekg** [comment]
Can you work in docker?

Is this an issue with clang vs gcc? What compiler and version are you using?

**Comment by foreveremain** [comment]
Clang 9.0.0 - sticking to a vanilla conda installation, but still running high sierra so base install may be old. I could run in docker of course but prefer not to if this is ending up as a conda recipe :)

**Comment by heuermh** [comment]
Thanks for making the new tag, @ekg!

Since my earlier comment above I fixed the build-from-source Docker image linked above (`heuermh/seqwish-dev` on Docker Hub) to work correctly with Nextflow.  I can also add a new Docker image based on the release tag (`heuermh/seqwish`) if that helps.

I am not a conda expert, however.  The only recipes I have done are for JVM or pyspark applications.

**Comment by foreveremain** [comment]
@heuermh - appreciate the update. I've given up on the osx build for the moment, since I'm supposed to be doing something else with that machine, but have (I think) a working conda build environment for seqwish now so it should be trivial to create the recipe. I'll come back to the osx build when I've done what I should have been doing in the last 4 hours :)

**Comment by heuermh** [comment]
Work in progress here https://github.com/bioconda/bioconda-recipes/pull/21199

**Comment by heuermh** [comment]
Fixed downstream, though the Bioconda recipe does not build on OSX.
