### ISSUE TITLE
"Missing" edges

### ISSUE THREAD

**Issue by fbemm** [ekg/seqwish#4]
Hi,

the seqwish GFA seems to miss some edges for loops:

P       4       34+,32-,32-,32-,344- # only a part of the path
S       32      G
L       32      +       32      +       OM
L       32      +       32      +       OM
L       32      +       32      -       OM
L       32      -       32      +       OM

Should'nt there be a:

L       32      -       32      -       OM

Works otherwise pretty great!

F

**Comment by ekg** [comment]
Has this been resolved? I was using vg view -Fv to detect when this
happens. I needed to add a mutex lock on a shared bitvector. Without it
this tended to happen.

**Comment by fbemm** [comment]
Testing with the latest commit atm. I keep you updated.

**Comment by fbemm** [comment]
```
*** Error in `seqwish': free(): invalid next size (normal): 0x0000152ac00009f0 ***
======= Backtrace: =========
[0x56ecd1]
[0x5779c6]
[0x57b9f7]
[0x53bfe9]
[0x4843be]
[0x484510]
[0x539544]
[0x53cf0c]
[0x53aa2a]
[0x548485]
[0x5bc719]
```

**Comment by fbemm** [comment]
The GFA file now contains:

```
St1_2.1 974421  890470  899546  +       St1_2.69        206126  126841  135687  5185    9098    0       cg:Z:
St1_2.1 974421  0       5649    +       St1_2.272       329270  323592  329254  4873    5675    0       cg:Z:
```

**Comment by fbemm** [comment]
I am not able to run seqwish on the above mentioned data set any more, and can't trace the reason for the segfault either. Switching back to an earlier release works (f75121a3b50a436ef394bb94d8672af69ae1545f).

**Comment by fbemm** [comment]
Switching from Ubuntu 16.04 to 18.04 solved the segfaults.

**Comment by ekg** [comment]
That's great! Can you work with the output graph?

**Comment by fbemm** [comment]
One thing that might be problematic is, that quite a number of links are simply duplicated. Currently testing if that solves the "duplicated rank" problem I always run into when indexing with vg.

**Comment by fbemm** [comment]
Yes. Just an example:

```
L       1504    +       34338705        -       OM
L       1504    +       1505    +       OM
L       1504    +       1505    +       OM
L       1505    +       1506    +       OM
```

Using a brute force sort it's about 3/4 of my links are actually duplicated exactly 2 times.

**Comment by fbemm** [comment]
This somehow disappeared.
