### ISSUE TITLE
Please release complete source code tarballs

### ISSUE THREAD

**Issue by mr-c** [ekg/seqwish#52]
Since `deps` contains git sub modules, this doesn't get picked up in the GitHub auto generated .tar.gz

Thanks,

-- 
The Debian-Med team

**Comment by ekg** [comment]
Yeah, this is annoying. I'll do so for the next release.

**Comment by AndreaGuarracino** [comment]
Hi @mr-c, the [current release](https://github.com/ekg/seqwish/releases/tag/v0.7.1) has a complete buildable source tarball.
