### ISSUE TITLE
Clarify behaviour with softmasked sequence

### ISSUE THREAD

**Issue by glennhickey** [ekg/seqwish#55]
`seqwish` seems to ignore alignments in the input PAF that contain softmasked/lowercase sequence in the fasta. 

I humbly suggest that this be turned off by default, and have it activated by command line option similarly to the other filters.  

Or, if leaving it default, just a mention of how it works in the README would be very helpful.

**Comment by ekg** [comment]
Yes, sorry about this. It would be an easy thing to patch by upper casing
the input sequences. It's even caught me up before. I was typically
preprocessing the FASTA inputs to resolve this, but that is tedious.

**Comment by ekg** [comment]
This should fix the usability issue.

Another thing is the rewriting of sequence names with the group prefix. That could just be done on the output graph, rather than on the input FASTAs.
