### ISSUE TITLE
Unable to compile seqwish

### ISSUE THREAD

**Issue by joyeuxnoel8** [ekg/seqwish#66]
Hi,

I'm trying to compile the most recent version 9bbfa70145e79777fc12cff6d0bad65d545f39fd using the suggested command `cmake -H. -Bbuild && cmake --build build -- -j 3` but failed with the following message.

```
Preprocessed source stored into /tmp/ccPsX3pE.out file, please attach this to your bugreport.
gmake[2]: *** [CMakeFiles/seqwish.dir/src/transclosure.cpp.o] Error 1
Preprocessed source stored into /tmp/ccg93yri.out file, please attach this to your bugreport.
gmake[2]: *** [CMakeFiles/seqwish.dir/src/main.cpp.o] Error 1
Preprocessed source stored into /tmp/cc2T9qbM.out file, please attach this to your bugreport.
gmake[2]: *** [CMakeFiles/seqwish.dir/src/links.cpp.o] Error 1
Preprocessed source stored into /tmp/ccQ8n05M.out file, please attach this to your bugreport.
gmake[2]: *** [CMakeFiles/seqwish.dir/src/compact.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/seqwish.dir/all] Error 2
gmake: *** [all] Error 2
```

The complete output of cmake and preprocessed source under /tmp/ are also attached in [log.tar.gz](https://github.com/ekg/seqwish/files/5319785/log.tar.gz).

Let me know how I can fix this. Thanks!

-Tony

**Comment by joyeuxnoel8** [comment]
Just to make it clear, I was trying to compile on CentOS Linux.

**Comment by joyeuxnoel8** [comment]
It turns out my latest version of `g++` is not under `/usr/bin`. Setting the correct path for `CC` and `CXX` in `~/.bashrc` like this,
```
export CC=/usr/usc/gnu/gcc/8.2.0/bin/gcc
export CXX=/usr/usc/gnu/gcc/8.2.0/bin/g++
```
, resolves the problem. Sorry to bug you with this trivial question!

**Comment by ekg** [comment]
Nice catch. Thank you!
