### ISSUE TITLE
No conda package for newer versions

### ISSUE THREAD

**Issue by gf-ho** [ekg/seqwish#81]
Hello.

I don't see the bioconda packages for versions later than 0.4.1, could you please add them?

**Comment by AndreaGuarracino** [comment]
In progress https://github.com/bioconda/bioconda-recipes/pull/29598

**Comment by gf-ho** [comment]
Thank you.

**Comment by AndreaGuarracino** [comment]
Thank you to you for using `seqwish`. The bioconda package update is completed: https://bioconda.github.io/recipes/seqwish/README.html
