### ISSUE TITLE
how to avoid having a cyclic graph

### ISSUE THREAD

**Issue by khodor14** [ekg/seqwish#95]
I'm using seqwish to construct a graph.

I used the commnad `seqwish -s genomes.fa -p alignment.paf.gz -g graph.gfa`

For `genomes.fa` I tried with 11 ecoli genomes for the first test. For the second test I used a reference then I imposed SNPs different positions to get 10 mutated copies of the reference. 

For the alignment, I'm using minimap2. 

My issue is that in both cases the graph turned out to be cyclic. 

I tried the option `-r 1` but still getting cyclic graph. 

Is there a way to avoid having cycles in the graph?

**Comment by ekg** [comment]
Avoiding all cycles will require that you build the graph with partial
order alignment. Do you want to avoid all cycles, or are you trying to
reduce their number? It's worth noting that bacterial genomes are cyclic so
in a general sense it won't be possible to eliminate all cycles.

**Comment by khodor14** [comment]
Thank you Erik for your quick reply.
> Do you want to avoid all cycles?
   I'm trying to align sequences using GraphChainer which does not accept cyclic graphs for the moment. So this why I'm trying to avoid cycles.

However for the test where I introduced SNPs to the genome, i believe  that it doesn't make sense to get cycles (i don't know but i will verify with acyclic genomes).

**Comment by ekg** [comment]
Please feel free to ping me by email. I'd be happy to discuss this further.

Another option is to use a mapper/aligner like wfmash. This is designed to
find maximum length homologies, and in general is easier to configure for
the graph building problem.
