### ISSUE TITLE
patch release for Bioconda?

### ISSUE THREAD

**Issue by rpetit3** [ekg/seqwish#97]
Hello! 

The tool `pggb` has started making use of your new `--temp-dir` parameter (https://github.com/pangenome/pggb/issues/208) which is not available in the current `seqwish` release on Bioconda. I was wondering if you would consider a small patch release so the Bioconda, users can make use of the Bioconda version of `pggb`.

Thank you very much for your time!
Robert

**Comment by rpetit3** [comment]
Thank you! I'll get the `pggb` recipe updated on Bioconda

**Comment by ekg** [comment]
Thank you!!!
